name: PyConES 2020 Online
tagline: PyConES 2020 Online<br> Pandemic Edition
date: 3 de octubre de 2020
citation_date: 3 de octubre de 2020
# proceedings_title: PyConES 2020 Online
analytics: 
logo:
  image: static/images/logo-pyes.png
  width: 40px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: PyConES 2020
page_title:
  prefix: 'PyConES 2020 Online'
  separator: ': '
background_image: static/images/main.jpg
organization: Grupo de Trabajo PyConES 2020 Online

# Remove or change to your chat server.
# chat_server: miniconf.sloppy.zone
# default_presentation_id: 38922815
# default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
